import { writeFileSync, existsSync, mkdirSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath, pathToFileURL } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const distDir = resolve(__dirname, "dist");

if (!existsSync(distDir)) {
  mkdirSync(distDir, { recursive: true });
}

const srcPath = pathToFileURL(resolve(distDir, "index.js")).href;
let defaultTokens;
try {
  defaultTokens = (await import(srcPath)).defaultTokens;
} catch (e) {
  console.warn("No compiled dist/index.js yet — skipping CSS generation.", e.message);
  process.exit(0);
}

function kebab(key) {
  return key.replace(/([A-Z])/g, "-$1").toLowerCase();
}

function isPlainObject(v) {
  return typeof v === "object" && v !== null && !Array.isArray(v);
}

function flattenTokens(obj, prefix = "") {
  const result = {};
  for (const [key, value] of Object.entries(obj)) {
    const path = prefix ? `${prefix}-${kebab(key)}` : kebab(key);
    if (isPlainObject(value)) {
      Object.assign(result, flattenTokens(value, path));
    } else {
      result[path] = String(value);
    }
  }
  return result;
}

function generateCSSVars(obj, selector) {
  const flat = flattenTokens(obj);
  const props = Object.entries(flat)
    .map(([name, value]) => `  --${name}: ${value};`)
    .join("\n");
  return `${selector} {\n${props}\n}\n`;
}

const { colors, ...rest } = defaultTokens;

const sharedVars = generateCSSVars(rest, ":root");
function generateColorVars(obj, selector) {
  const flat = flattenTokens(obj, "color");
  const props = Object.entries(flat)
    .map(([name, value]) => `  --${name}: ${value};`)
    .join("\n");
  return `${selector} {\n${props}\n}\n`;
}
const lightVars = generateColorVars(colors.light, ":root");
const darkVars = generateColorVars(colors.dark, ".dark");

const css = `/* Auto-generated by build-tokens.mjs — do not edit */
@layer base {
${sharedVars}
${lightVars}
${darkVars}
}
`;

writeFileSync(resolve(distDir, "tokens.css"), css, "utf-8");
console.log("Generated dist/tokens.css");
