import type { DesignTokens } from "@commerceos/design-tokens";
import { defaultTokens } from "@commerceos/design-tokens";

export const amberSunsetTheme: Partial<DesignTokens> = {
  colors: {
    light: {
      muted: {
        background: "#fffbeb",
        foreground: "#78350f",
        card: "#ffffff",
        cardForeground: "#78350f",
        popover: "#ffffff",
        popoverForeground: "#78350f",
        primary: "#d97706",
        primaryForeground: "#ffffff",
        secondary: "#fef3c7",
        secondaryForeground: "#92400e",
        muted: "#fef3c7",
        mutedForeground: "#b45309",
        accent: "#ea580c",
        accentForeground: "#ffffff",
        destructive: "#dc2626",
        destructiveForeground: "#ffffff",
        border: "#fde68a",
        input: "#fde68a",
        ring: "#d97706",
      },
      colorful: {
        background: "#fffbeb",
        foreground: "#78350f",
        card: "#ffffff",
        cardForeground: "#78350f",
        popover: "#ffffff",
        popoverForeground: "#78350f",
        primary: "#b45309",
        primaryForeground: "#ffffff",
        secondary: "#fde68a",
        secondaryForeground: "#78350f",
        muted: "#fef3c7",
        mutedForeground: "#92400e",
        accent: "#c2410c",
        accentForeground: "#ffffff",
        destructive: "#dc2626",
        destructiveForeground: "#ffffff",
        border: "#fcd34d",
        input: "#fcd34d",
        ring: "#b45309",
      },
    },
    dark: {
      muted: {
        background: "#1c1002",
        foreground: "#fffbeb",
        card: "#451a03",
        cardForeground: "#fffbeb",
        popover: "#451a03",
        popoverForeground: "#fffbeb",
        primary: "#f59e0b",
        primaryForeground: "#1c1002",
        secondary: "#78350f",
        secondaryForeground: "#fef3c7",
        muted: "#78350f",
        mutedForeground: "#fde68a",
        accent: "#f97316",
        accentForeground: "#1c1002",
        destructive: "#ef4444",
        destructiveForeground: "#ffffff",
        border: "#78350f",
        input: "#78350f",
        ring: "#f59e0b",
      },
      colorful: {
        background: "#1c1002",
        foreground: "#fffbeb",
        card: "#451a03",
        cardForeground: "#fffbeb",
        popover: "#451a03",
        popoverForeground: "#fffbeb",
        primary: "#fbbf24",
        primaryForeground: "#1c1002",
        secondary: "#b45309",
        secondaryForeground: "#ffffff",
        muted: "#92400e",
        mutedForeground: "#fde68a",
        accent: "#fb923c",
        accentForeground: "#1c1002",
        destructive: "#ef4444",
        destructiveForeground: "#ffffff",
        border: "#92400e",
        input: "#92400e",
        ring: "#fbbf24",
      },
    },
  },
  typography: {
    ...defaultTokens.typography,
    fontFamilies: {
      sans: "'Work Sans', sans-serif",
      heading: "'Lora', serif",
      mono: "monospace",
    },
  },
  radii: {
    none: "0",
    sm: "6px",
    md: "12px",
    lg: "18px",
    xl: "24px",
    "2xl": "32px",
    full: "9999px",
  },
};
