import type { DesignTokens } from "@commerceos/design-tokens";
import { defaultTokens } from "@commerceos/design-tokens";

export const boldTheme: Partial<DesignTokens> = {
  colors: {
    dark: {
      muted: {
        background: "#1e3a8a",
        foreground: "#fef3c7",
        card: "#172554",
        cardForeground: "#fef3c7",
        popover: "#172554",
        popoverForeground: "#fef3c7",
        primary: "#dc2626",
        primaryForeground: "#ffffff",
        secondary: "#1e40af",
        secondaryForeground: "#fef3c7",
        muted: "#1e40af",
        mutedForeground: "#fde68a",
        accent: "#ea580c",
        accentForeground: "#ffffff",
        destructive: "#ef4444",
        destructiveForeground: "#ffffff",
        border: "#1e40af",
        input: "#1e40af",
        ring: "#dc2626",
      },
      colorful: {
        background: "#1e3a8a",
        foreground: "#fef3c7",
        card: "#172554",
        cardForeground: "#fef3c7",
        popover: "#172554",
        popoverForeground: "#fef3c7",
        primary: "#dc2626",
        primaryForeground: "#ffffff",
        secondary: "#1e40af",
        secondaryForeground: "#fef3c7",
        muted: "#1e40af",
        mutedForeground: "#fde68a",
        accent: "#ea580c",
        accentForeground: "#ffffff",
        destructive: "#ef4444",
        destructiveForeground: "#ffffff",
        border: "#1e40af",
        input: "#1e40af",
        ring: "#dc2626",
      },
    },
    light: {
      muted: {
        background: "#fef3c7",
        foreground: "#1e3a8a",
        card: "#fde68a",
        cardForeground: "#1e3a8a",
        popover: "#fde68a",
        popoverForeground: "#1e3a8a",
        primary: "#dc2626",
        primaryForeground: "#ffffff",
        secondary: "#fbbf24",
        secondaryForeground: "#1e3a8a",
        muted: "#fbbf24",
        mutedForeground: "#1d4ed8",
        accent: "#ea580c",
        accentForeground: "#ffffff",
        destructive: "#ef4444",
        destructiveForeground: "#ffffff",
        border: "#fbbf24",
        input: "#fbbf24",
        ring: "#dc2626",
      },
      colorful: {
        background: "#fef3c7",
        foreground: "#1e3a8a",
        card: "#fde68a",
        cardForeground: "#1e3a8a",
        popover: "#fde68a",
        popoverForeground: "#1e3a8a",
        primary: "#dc2626",
        primaryForeground: "#ffffff",
        secondary: "#fbbf24",
        secondaryForeground: "#1e3a8a",
        muted: "#fbbf24",
        mutedForeground: "#1d4ed8",
        accent: "#ea580c",
        accentForeground: "#ffffff",
        destructive: "#ef4444",
        destructiveForeground: "#ffffff",
        border: "#fbbf24",
        input: "#fbbf24",
        ring: "#dc2626",
      },
    },
  },
  typography: {
    ...defaultTokens.typography,
    fontFamilies: {
      sans: "Oswald, sans-serif",
      mono: "monospace",
      heading: "Oswald, sans-serif",
    },
  },
  radii: {
    none: "0",
    sm: "12px",
    md: "24px",
    lg: "32px",
    xl: "48px",
    "2xl": "64px",
    full: "9999px",
  }
};