import type { DesignTokens } from "@commerceos/design-tokens";
import { defaultTokens } from "@commerceos/design-tokens";

export const darkModeProTheme: Partial<DesignTokens> = {
  colors: {
    light: {
      muted: {
        background: "#090d16",
        foreground: "#f8fafc",
        card: "#0f172a",
        cardForeground: "#f8fafc",
        popover: "#0f172a",
        popoverForeground: "#f8fafc",
        primary: "#38bdf8",
        primaryForeground: "#090d16",
        secondary: "#1e293b",
        secondaryForeground: "#f8fafc",
        muted: "#1e293b",
        mutedForeground: "#94a3b8",
        accent: "#818cf8",
        accentForeground: "#090d16",
        destructive: "#f87171",
        destructiveForeground: "#090d16",
        border: "#1e293b",
        input: "#1e293b",
        ring: "#38bdf8",
      },
      colorful: {
        background: "#090d16",
        foreground: "#f8fafc",
        card: "#0f172a",
        cardForeground: "#f8fafc",
        popover: "#0f172a",
        popoverForeground: "#f8fafc",
        primary: "#38bdf8",
        primaryForeground: "#090d16",
        secondary: "#1e293b",
        secondaryForeground: "#f8fafc",
        muted: "#1e293b",
        mutedForeground: "#94a3b8",
        accent: "#818cf8",
        accentForeground: "#090d16",
        destructive: "#f87171",
        destructiveForeground: "#090d16",
        border: "#1e293b",
        input: "#1e293b",
        ring: "#38bdf8",
      },
    },
    dark: {
      muted: {
        background: "#090d16",
        foreground: "#f8fafc",
        card: "#0f172a",
        cardForeground: "#f8fafc",
        popover: "#0f172a",
        popoverForeground: "#f8fafc",
        primary: "#38bdf8",
        primaryForeground: "#090d16",
        secondary: "#1e293b",
        secondaryForeground: "#f8fafc",
        muted: "#1e293b",
        mutedForeground: "#94a3b8",
        accent: "#818cf8",
        accentForeground: "#090d16",
        destructive: "#f87171",
        destructiveForeground: "#090d16",
        border: "#1e293b",
        input: "#1e293b",
        ring: "#38bdf8",
      },
      colorful: {
        background: "#090d16",
        foreground: "#f8fafc",
        card: "#0f172a",
        cardForeground: "#f8fafc",
        popover: "#0f172a",
        popoverForeground: "#f8fafc",
        primary: "#38bdf8",
        primaryForeground: "#090d16",
        secondary: "#1e293b",
        secondaryForeground: "#f8fafc",
        muted: "#1e293b",
        mutedForeground: "#94a3b8",
        accent: "#818cf8",
        accentForeground: "#090d16",
        destructive: "#f87171",
        destructiveForeground: "#090d16",
        border: "#1e293b",
        input: "#1e293b",
        ring: "#38bdf8",
      },
    },
  },
  typography: {
    ...defaultTokens.typography,
    fontFamilies: {
      sans: "'Inter', sans-serif",
      heading: "'Space Grotesk', sans-serif",
      mono: "'JetBrains Mono', monospace",
    },
  },
  radii: {
    none: "0",
    sm: "6px",
    md: "10px",
    lg: "16px",
    xl: "24px",
    "2xl": "32px",
    full: "9999px",
  },
};
