import type { DesignTokens } from "@commerceos/design-tokens";
import { defaultTokens } from "@commerceos/design-tokens";

export const emeraldLuxeTheme: Partial<DesignTokens> = {
  colors: {
    light: {
      muted: {
        background: "#f4fdf8",
        foreground: "#064e3b",
        card: "#ffffff",
        cardForeground: "#064e3b",
        popover: "#ffffff",
        popoverForeground: "#064e3b",
        primary: "#059669",
        primaryForeground: "#ffffff",
        secondary: "#d1fae5",
        secondaryForeground: "#065f46",
        muted: "#e6f4ed",
        mutedForeground: "#047857",
        accent: "#d97706",
        accentForeground: "#ffffff",
        destructive: "#e11d48",
        destructiveForeground: "#ffffff",
        border: "#a7f3d0",
        input: "#a7f3d0",
        ring: "#059669",
      },
      colorful: {
        background: "#ecfdf5",
        foreground: "#064e3b",
        card: "#ffffff",
        cardForeground: "#064e3b",
        popover: "#ffffff",
        popoverForeground: "#064e3b",
        primary: "#059669",
        primaryForeground: "#ffffff",
        secondary: "#a7f3d0",
        secondaryForeground: "#064e3b",
        muted: "#d1fae5",
        mutedForeground: "#047857",
        accent: "#d97706",
        accentForeground: "#ffffff",
        destructive: "#e11d48",
        destructiveForeground: "#ffffff",
        border: "#a7f3d0",
        input: "#a7f3d0",
        ring: "#059669",
      },
    },
    dark: {
      muted: {
        background: "#022c22",
        foreground: "#ecfdf5",
        card: "#064e3b",
        cardForeground: "#ecfdf5",
        popover: "#064e3b",
        popoverForeground: "#ecfdf5",
        primary: "#10b981",
        primaryForeground: "#022c22",
        secondary: "#047857",
        secondaryForeground: "#ecfdf5",
        muted: "#065f46",
        mutedForeground: "#a7f3d0",
        accent: "#f59e0b",
        accentForeground: "#022c22",
        destructive: "#f43f5e",
        destructiveForeground: "#ffffff",
        border: "#047857",
        input: "#047857",
        ring: "#10b981",
      },
      colorful: {
        background: "#022c22",
        foreground: "#ecfdf5",
        card: "#064e3b",
        cardForeground: "#ecfdf5",
        popover: "#064e3b",
        popoverForeground: "#ecfdf5",
        primary: "#10b981",
        primaryForeground: "#022c22",
        secondary: "#047857",
        secondaryForeground: "#ecfdf5",
        muted: "#065f46",
        mutedForeground: "#a7f3d0",
        accent: "#f59e0b",
        accentForeground: "#022c22",
        destructive: "#f43f5e",
        destructiveForeground: "#ffffff",
        border: "#047857",
        input: "#047857",
        ring: "#10b981",
      },
    },
  },
  typography: {
    ...defaultTokens.typography,
    fontFamilies: {
      sans: "'Plus Jakarta Sans', sans-serif",
      heading: "'Cormorant Garamond', serif",
      mono: "monospace",
    },
  },
  radii: {
    none: "0",
    sm: "4px",
    md: "8px",
    lg: "16px",
    xl: "24px",
    "2xl": "32px",
    full: "9999px",
  },
};
