import type { DesignTokens } from "@commerceos/design-tokens";
import { defaultTokens } from "@commerceos/design-tokens";

export const highContrastTheme: Partial<DesignTokens> = {
  colors: {
    light: {
      muted: {
        background: "#ffffff",
        foreground: "#000000",
        card: "#ffffff",
        cardForeground: "#000000",
        popover: "#ffffff",
        popoverForeground: "#000000",
        primary: "#000000",
        primaryForeground: "#ffffff",
        secondary: "#e2e8f0",
        secondaryForeground: "#000000",
        muted: "#f1f5f9",
        mutedForeground: "#000000",
        accent: "#000000",
        accentForeground: "#ffffff",
        destructive: "#b91c1c",
        destructiveForeground: "#ffffff",
        border: "#000000",
        input: "#000000",
        ring: "#000000",
      },
      colorful: {
        background: "#ffffff",
        foreground: "#000000",
        card: "#ffffff",
        cardForeground: "#000000",
        popover: "#ffffff",
        popoverForeground: "#000000",
        primary: "#000000",
        primaryForeground: "#ffffff",
        secondary: "#e2e8f0",
        secondaryForeground: "#000000",
        muted: "#f1f5f9",
        mutedForeground: "#000000",
        accent: "#000000",
        accentForeground: "#ffffff",
        destructive: "#b91c1c",
        destructiveForeground: "#ffffff",
        border: "#000000",
        input: "#000000",
        ring: "#000000",
      },
    },
    dark: {
      muted: {
        background: "#000000",
        foreground: "#ffffff",
        card: "#000000",
        cardForeground: "#ffffff",
        popover: "#000000",
        popoverForeground: "#ffffff",
        primary: "#ffffff",
        primaryForeground: "#000000",
        secondary: "#1e293b",
        secondaryForeground: "#ffffff",
        muted: "#0f172a",
        mutedForeground: "#ffffff",
        accent: "#ffffff",
        accentForeground: "#000000",
        destructive: "#f87171",
        destructiveForeground: "#000000",
        border: "#ffffff",
        input: "#ffffff",
        ring: "#ffffff",
      },
      colorful: {
        background: "#000000",
        foreground: "#ffffff",
        card: "#000000",
        cardForeground: "#ffffff",
        popover: "#000000",
        popoverForeground: "#ffffff",
        primary: "#ffffff",
        primaryForeground: "#000000",
        secondary: "#1e293b",
        secondaryForeground: "#ffffff",
        muted: "#0f172a",
        mutedForeground: "#ffffff",
        accent: "#ffffff",
        accentForeground: "#000000",
        destructive: "#f87171",
        destructiveForeground: "#000000",
        border: "#ffffff",
        input: "#ffffff",
        ring: "#ffffff",
      },
    },
  },
  typography: {
    ...defaultTokens.typography,
    fontFamilies: {
      sans: "Arial, sans-serif",
      heading: "Arial, sans-serif",
      mono: "monospace",
    },
  },
  radii: {
    none: "0",
    sm: "2px",
    md: "4px",
    lg: "6px",
    xl: "8px",
    "2xl": "12px",
    full: "9999px",
  },
};
