import type { DesignTokens } from "@commerceos/design-tokens";
import { defaultTokens } from "@commerceos/design-tokens";

export const minimalTheme: Partial<DesignTokens> = {
  colors: {
    dark: {
      muted: {
        background: "#000000",
        foreground: "#ffffff",
        card: "#111111",
        cardForeground: "#ffffff",
        popover: "#111111",
        popoverForeground: "#ffffff",
        primary: "#ffffff",
        primaryForeground: "#000000",
        secondary: "#111111",
        secondaryForeground: "#ffffff",
        muted: "#111111",
        mutedForeground: "#888888",
        accent: "#ffffff",
        accentForeground: "#000000",
        destructive: "#ffffff",
        destructiveForeground: "#000000",
        border: "#333333",
        input: "#333333",
        ring: "#ffffff",
      },
      colorful: {
        background: "#000000",
        foreground: "#ffffff",
        card: "#111111",
        cardForeground: "#ffffff",
        popover: "#111111",
        popoverForeground: "#ffffff",
        primary: "#ffffff",
        primaryForeground: "#000000",
        secondary: "#111111",
        secondaryForeground: "#ffffff",
        muted: "#111111",
        mutedForeground: "#888888",
        accent: "#ffffff",
        accentForeground: "#000000",
        destructive: "#ffffff",
        destructiveForeground: "#000000",
        border: "#333333",
        input: "#333333",
        ring: "#ffffff",
      },
    },
    light: {
      muted: {
        background: "#ffffff",
        foreground: "#000000",
        card: "#fafafa",
        cardForeground: "#000000",
        popover: "#fafafa",
        popoverForeground: "#000000",
        primary: "#000000",
        primaryForeground: "#ffffff",
        secondary: "#fafafa",
        secondaryForeground: "#000000",
        muted: "#fafafa",
        mutedForeground: "#666666",
        accent: "#000000",
        accentForeground: "#ffffff",
        destructive: "#000000",
        destructiveForeground: "#ffffff",
        border: "#eaeaea",
        input: "#eaeaea",
        ring: "#000000",
      },
      colorful: {
        background: "#ffffff",
        foreground: "#000000",
        card: "#fafafa",
        cardForeground: "#000000",
        popover: "#fafafa",
        popoverForeground: "#000000",
        primary: "#000000",
        primaryForeground: "#ffffff",
        secondary: "#fafafa",
        secondaryForeground: "#000000",
        muted: "#fafafa",
        mutedForeground: "#666666",
        accent: "#000000",
        accentForeground: "#ffffff",
        destructive: "#000000",
        destructiveForeground: "#ffffff",
        border: "#eaeaea",
        input: "#eaeaea",
        ring: "#000000",
      },
    },
  },
  typography: {
    ...defaultTokens.typography,
    fontFamilies: {
      sans: "Inter, sans-serif",
      mono: "monospace",
      heading: "Inter, sans-serif",
    },
  },
  radii: {
    none: "0",
    sm: "0",
    md: "0",
    lg: "0",
    xl: "0",
    "2xl": "0",
    full: "0",
  }
};