import type { DesignTokens } from "@commerceos/design-tokens";
import { defaultTokens } from "@commerceos/design-tokens";

export const pastelBeautyTheme: Partial<DesignTokens> = {
  colors: {
    light: {
      muted: {
        background: "#fffafb",
        foreground: "#881337",
        card: "#ffffff",
        cardForeground: "#881337",
        popover: "#ffffff",
        popoverForeground: "#881337",
        primary: "#e11d48",
        primaryForeground: "#ffffff",
        secondary: "#ffe4e6",
        secondaryForeground: "#9f1239",
        muted: "#ffe4e6",
        mutedForeground: "#be123c",
        accent: "#fb7185",
        accentForeground: "#ffffff",
        destructive: "#dc2626",
        destructiveForeground: "#ffffff",
        border: "#fecdd3",
        input: "#fecdd3",
        ring: "#e11d48",
      },
      colorful: {
        background: "#fff1f2",
        foreground: "#881337",
        card: "#ffffff",
        cardForeground: "#881337",
        popover: "#ffffff",
        popoverForeground: "#881337",
        primary: "#be123c",
        primaryForeground: "#ffffff",
        secondary: "#fecdd3",
        secondaryForeground: "#881337",
        muted: "#ffe4e6",
        mutedForeground: "#9f1239",
        accent: "#f43f5e",
        accentForeground: "#ffffff",
        destructive: "#dc2626",
        destructiveForeground: "#ffffff",
        border: "#fda4af",
        input: "#fda4af",
        ring: "#be123c",
      },
    },
    dark: {
      muted: {
        background: "#2a0812",
        foreground: "#fff1f2",
        card: "#4c0519",
        cardForeground: "#fff1f2",
        popover: "#4c0519",
        popoverForeground: "#fff1f2",
        primary: "#fb7185",
        primaryForeground: "#2a0812",
        secondary: "#881337",
        secondaryForeground: "#ffe4e6",
        muted: "#581c87",
        mutedForeground: "#fecdd3",
        accent: "#f43f5e",
        accentForeground: "#ffffff",
        destructive: "#f87171",
        destructiveForeground: "#000000",
        border: "#881337",
        input: "#881337",
        ring: "#fb7185",
      },
      colorful: {
        background: "#2a0812",
        foreground: "#fff1f2",
        card: "#4c0519",
        cardForeground: "#fff1f2",
        popover: "#4c0519",
        popoverForeground: "#fff1f2",
        primary: "#f43f5e",
        primaryForeground: "#ffffff",
        secondary: "#9f1239",
        secondaryForeground: "#ffffff",
        muted: "#881337",
        mutedForeground: "#fda4af",
        accent: "#fb7185",
        accentForeground: "#2a0812",
        destructive: "#f87171",
        destructiveForeground: "#000000",
        border: "#9f1239",
        input: "#9f1239",
        ring: "#f43f5e",
      },
    },
  },
  typography: {
    ...defaultTokens.typography,
    fontFamilies: {
      sans: "'DM Sans', sans-serif",
      heading: "'Playfair Display', serif",
      mono: "monospace",
    },
  },
  radii: {
    none: "0",
    sm: "10px",
    md: "16px",
    lg: "24px",
    xl: "32px",
    "2xl": "44px",
    full: "9999px",
  },
};
