import type { DesignTokens } from "@commerceos/design-tokens";
import { defaultTokens } from "@commerceos/design-tokens";

export const sapphireRoyalTheme: Partial<DesignTokens> = {
  colors: {
    light: {
      muted: {
        background: "#f0f7ff",
        foreground: "#0f172a",
        card: "#ffffff",
        cardForeground: "#0f172a",
        popover: "#ffffff",
        popoverForeground: "#0f172a",
        primary: "#2563eb",
        primaryForeground: "#ffffff",
        secondary: "#dbeafe",
        secondaryForeground: "#1e40af",
        muted: "#e2e8f0",
        mutedForeground: "#475569",
        accent: "#0284c7",
        accentForeground: "#ffffff",
        destructive: "#dc2626",
        destructiveForeground: "#ffffff",
        border: "#bfdbfe",
        input: "#bfdbfe",
        ring: "#2563eb",
      },
      colorful: {
        background: "#eff6ff",
        foreground: "#0f172a",
        card: "#ffffff",
        cardForeground: "#0f172a",
        popover: "#ffffff",
        popoverForeground: "#0f172a",
        primary: "#1d4ed8",
        primaryForeground: "#ffffff",
        secondary: "#bfdbfe",
        secondaryForeground: "#1e3a8a",
        muted: "#dbeafe",
        mutedForeground: "#1e40af",
        accent: "#0369a1",
        accentForeground: "#ffffff",
        destructive: "#dc2626",
        destructiveForeground: "#ffffff",
        border: "#93c5fd",
        input: "#93c5fd",
        ring: "#1d4ed8",
      },
    },
    dark: {
      muted: {
        background: "#0b1329",
        foreground: "#f8fafc",
        card: "#1e293b",
        cardForeground: "#f8fafc",
        popover: "#1e293b",
        popoverForeground: "#f8fafc",
        primary: "#3b82f6",
        primaryForeground: "#ffffff",
        secondary: "#1e3a8a",
        secondaryForeground: "#dbeafe",
        muted: "#334155",
        mutedForeground: "#94a3b8",
        accent: "#38bdf8",
        accentForeground: "#0f172a",
        destructive: "#f87171",
        destructiveForeground: "#0f172a",
        border: "#334155",
        input: "#334155",
        ring: "#3b82f6",
      },
      colorful: {
        background: "#0f172a",
        foreground: "#f8fafc",
        card: "#1e293b",
        cardForeground: "#f8fafc",
        popover: "#1e293b",
        popoverForeground: "#f8fafc",
        primary: "#60a5fa",
        primaryForeground: "#0f172a",
        secondary: "#1d4ed8",
        secondaryForeground: "#ffffff",
        muted: "#1e3a8a",
        mutedForeground: "#93c5fd",
        accent: "#38bdf8",
        accentForeground: "#0f172a",
        destructive: "#f87171",
        destructiveForeground: "#0f172a",
        border: "#1d4ed8",
        input: "#1d4ed8",
        ring: "#60a5fa",
      },
    },
  },
  typography: {
    ...defaultTokens.typography,
    fontFamilies: {
      sans: "'Outfit', sans-serif",
      heading: "'Outfit', sans-serif",
      mono: "monospace",
    },
  },
  radii: {
    none: "0",
    sm: "6px",
    md: "10px",
    lg: "16px",
    xl: "20px",
    "2xl": "28px",
    full: "9999px",
  },
};
