import type { DesignTokens } from "@commerceos/design-tokens";
import { defaultTokens } from "@commerceos/design-tokens";

export const violetGlowTheme: Partial<DesignTokens> = {
  colors: {
    light: {
      muted: {
        background: "#faf5ff",
        foreground: "#3b0764",
        card: "#ffffff",
        cardForeground: "#3b0764",
        popover: "#ffffff",
        popoverForeground: "#3b0764",
        primary: "#9333ea",
        primaryForeground: "#ffffff",
        secondary: "#f3e8ff",
        secondaryForeground: "#6b21a8",
        muted: "#f3e8ff",
        mutedForeground: "#7e22ce",
        accent: "#d946ef",
        accentForeground: "#ffffff",
        destructive: "#e11d48",
        destructiveForeground: "#ffffff",
        border: "#e9d5ff",
        input: "#e9d5ff",
        ring: "#9333ea",
      },
      colorful: {
        background: "#faf5ff",
        foreground: "#3b0764",
        card: "#ffffff",
        cardForeground: "#3b0764",
        popover: "#ffffff",
        popoverForeground: "#3b0764",
        primary: "#7e22ce",
        primaryForeground: "#ffffff",
        secondary: "#e9d5ff",
        secondaryForeground: "#3b0764",
        muted: "#f3e8ff",
        mutedForeground: "#6b21a8",
        accent: "#c084fc",
        accentForeground: "#3b0764",
        destructive: "#e11d48",
        destructiveForeground: "#ffffff",
        border: "#d8b4fe",
        input: "#d8b4fe",
        ring: "#7e22ce",
      },
    },
    dark: {
      muted: {
        background: "#19072b",
        foreground: "#faf5ff",
        card: "#2e1065",
        cardForeground: "#faf5ff",
        popover: "#2e1065",
        popoverForeground: "#faf5ff",
        primary: "#a855f7",
        primaryForeground: "#ffffff",
        secondary: "#581c87",
        secondaryForeground: "#f3e8ff",
        muted: "#3b0764",
        mutedForeground: "#d8b4fe",
        accent: "#e879f9",
        accentForeground: "#19072b",
        destructive: "#fb7185",
        destructiveForeground: "#19072b",
        border: "#581c87",
        input: "#581c87",
        ring: "#a855f7",
      },
      colorful: {
        background: "#0f051d",
        foreground: "#faf5ff",
        card: "#2e1065",
        cardForeground: "#faf5ff",
        popover: "#2e1065",
        popoverForeground: "#faf5ff",
        primary: "#c084fc",
        primaryForeground: "#0f051d",
        secondary: "#7e22ce",
        secondaryForeground: "#ffffff",
        muted: "#581c87",
        mutedForeground: "#e9d5ff",
        accent: "#f0abfc",
        accentForeground: "#0f051d",
        destructive: "#fb7185",
        destructiveForeground: "#0f051d",
        border: "#7e22ce",
        input: "#7e22ce",
        ring: "#c084fc",
      },
    },
  },
  typography: {
    ...defaultTokens.typography,
    fontFamilies: {
      sans: "'Space Grotesk', sans-serif",
      heading: "'Space Grotesk', sans-serif",
      mono: "'JetBrains Mono', monospace",
    },
  },
  radii: {
    none: "0",
    sm: "8px",
    md: "14px",
    lg: "20px",
    xl: "28px",
    "2xl": "36px",
    full: "9999px",
  },
};
