module.exports = {
  theme: {
    extend: {
      colors: {
        surface: "var(--color-surface)",
        surfaceMuted: "var(--color-surface-muted)",
        text: "var(--color-text)",
        textMuted: "var(--color-text-muted)",
        border: "var(--color-border)",
        primary: "var(--color-primary)",
        primaryContrast: "var(--color-primary-contrast)",
        accent: "var(--color-accent)",
        accentContrast: "var(--color-accent-contrast)",
        success: "var(--color-success)",
        successContrast: "var(--color-success-contrast)",
        warning: "var(--color-warning)",
        warningContrast: "var(--color-warning-contrast)",
        error: "var(--color-error)",
        errorContrast: "var(--color-error-contrast)",
      },
      spacing: {
        "0.5": "var(--spacing-0-5)",
        "1": "var(--spacing-1)",
        "1.5": "var(--spacing-1-5)",
        "2": "var(--spacing-2)",
        "2.5": "var(--spacing-2-5)",
        "3": "var(--spacing-3)",
        "3.5": "var(--spacing-3-5)",
        "4": "var(--spacing-4)",
        "5": "var(--spacing-5)",
        "6": "var(--spacing-6)",
        "7": "var(--spacing-7)",
        "8": "var(--spacing-8)",
        "9": "var(--spacing-9)",
        "10": "var(--spacing-10)",
        "11": "var(--spacing-11)",
        "12": "var(--spacing-12)",
        "14": "var(--spacing-14)",
        "16": "var(--spacing-16)",
        "20": "var(--spacing-20)",
        "24": "var(--spacing-24)",
        "28": "var(--spacing-28)",
        "32": "var(--spacing-32)",
        "36": "var(--spacing-36)",
        "40": "var(--spacing-40)",
        "44": "var(--spacing-44)",
        "48": "var(--spacing-48)",
        "52": "var(--spacing-52)",
        "56": "var(--spacing-56)",
        "60": "var(--spacing-60)",
        "64": "var(--spacing-64)",
        "72": "var(--spacing-72)",
        "80": "var(--spacing-80)",
        "96": "var(--spacing-96)",
      },
      fontFamily: {
        sans: "var(--typography-font-families-sans)",
        mono: "var(--typography-font-families-mono)",
        heading: "var(--typography-font-families-heading)",
      },
      fontSize: {
        xs: "var(--typography-font-sizes-xs)",
        sm: "var(--typography-font-sizes-sm)",
        base: "var(--typography-font-sizes-base)",
        lg: "var(--typography-font-sizes-lg)",
        xl: "var(--typography-font-sizes-xl)",
        "2xl": "var(--typography-font-sizes-2xl)",
        "3xl": "var(--typography-font-sizes-3xl)",
        "4xl": "var(--typography-font-sizes-4xl)",
        "5xl": "var(--typography-font-sizes-5xl)",
        "6xl": "var(--typography-font-sizes-6xl)",
      },
      fontWeight: {
        normal: "var(--typography-font-weights-normal)",
        medium: "var(--typography-font-weights-medium)",
        semibold: "var(--typography-font-weights-semibold)",
        bold: "var(--typography-font-weights-bold)",
      },
      lineHeight: {
        none: "var(--typography-line-heights-none)",
        tight: "var(--typography-line-heights-tight)",
        snug: "var(--typography-line-heights-snug)",
        normal: "var(--typography-line-heights-normal)",
        relaxed: "var(--typography-line-heights-relaxed)",
        loose: "var(--typography-line-heights-loose)",
      },
      letterSpacing: {
        tight: "var(--typography-letter-spacings-tight)",
        normal: "var(--typography-letter-spacings-normal)",
        wide: "var(--typography-letter-spacings-wide)",
      },
      boxShadow: {
        sm: "var(--shadows-sm)",
        md: "var(--shadows-md)",
        lg: "var(--shadows-lg)",
        xl: "var(--shadows-xl)",
        "2xl": "var(--shadows-2xl)",
        inner: "var(--shadows-inner)",
      },
      borderRadius: {
        none: "var(--radii-none)",
        sm: "var(--radii-sm)",
        md: "var(--radii-md)",
        lg: "var(--radii-lg)",
        xl: "var(--radii-xl)",
        "2xl": "var(--radii-2xl)",
        full: "var(--radii-full)",
      },
      screens: {
        sm: "var(--breakpoints-sm)",
        md: "var(--breakpoints-md)",
        lg: "var(--breakpoints-lg)",
        xl: "var(--breakpoints-xl)",
        "2xl": "var(--breakpoints-2xl)",
      },
    },
  },
  plugins: [],
};
